# ln ~/.config/alacritty/alacritty.toml

[window]
padding = { x = 3, y = 3 }

[font]
size = 9

[colors.primary]
background = "#1b2730"

[keyboard]
bindings = [
  { key = "Return", mods = "Super|Shift", action = "SpawnNewInstance" }
]
