# ln ~/.config/helix/config.toml

theme = "custom"

[editor]
true-color = true
auto-format = false
completion-trigger-len = 1

[editor.lsp]
snippets = true
display-color-swatches = false

[editor.file-picker]
hidden = false

[keys.insert.j]
k = "normal_mode"

[keys.insert.k]
j = "normal_mode"

[keys.normal]
C-f = ":format"
