# ln ~/.config/helix/languages.toml

# defaults: https://github.com/helix-editor/helix/blob/master/languages.toml

[language-server]
hxlsp = { command = "hx-lsp" }
oxfmt = { command = "oxfmt", args = ["--lsp"] }
oxlint = { command = "oxlint", args = ["--lsp"] }

[[language]]
name = "html"
language-servers = [
  "vscode-html-language-server",
  { name = "hxlsp", only-features = [
    "completion",
  ] },
]

[[language]]
name = "typescript"
language-servers = ["oxfmt", "oxlint", "typescript-language-server"]
